@startuml
title "C4. Контекст"

!include <C4/C4_Container>

Person(driver, "Водитель", "Просматривает парковки, бронирует парковки, находит ближайшие парковки, оплачивает парковку")
Person(operator, "Оператор", "Управляют данными пользователей, обрабатывают жалобы и обращения")
Person(admin, "Администратор", "Управление учетными записями пользователей, настройка системы, анализ данных о посещениях и выданных книгах.")

System(parkingSystem, "Система парковок")
driver ---> parkingSystem
operator ---> parkingSystem
admin ---> parkingSystem

System_Ext(email, "Email сервис", "отправка уведомлений")
System_Ext(maps, "Провайдер карт", "Предоставление ближайшего маршрута, карт")
System_Ext(geocoder, "Геокодер", "Предоставление адреса по координатам, и наоборот")
System_Ext(paymentSystem, "Платёжная система", "Предоставление возможности оплаты и рекуррентных платежей")

parkingSystem --> email
parkingSystem --> maps
parkingSystem --> geocoder
parkingSystem --> paymentSystem
@enduml