@startuml Диаграмма контекста
title "C4. Контекст"

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!$ICONURL = "https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v3.0.0/icons"
!include $ICONURL/common.puml
!include $ICONURL/devicons/react.puml
!include $ICONURL/devicons/php.puml
!include $ICONURL/devicons2/sqlite.puml



Person(reader, "Читатель", "Просматр каталога и поиск в нем книг, бронирование книги")
Person(librarin, "Библиотекарь", "Учет новых поступлений книг, выдача книг читателям, прием возвращенных книг, учет штрафов за просроченный возврат")
Person(admin, "Администратор", "Управление учетными записями пользователей, настройка системы, анализ данных о посещениях и выданных книгах.")

System(libAcc, "Система учета библиотеки")
Rel(reader, libAcc, "")
Rel(librarin, libAcc, "")
Rel(admin, libAcc, "")

System_Ext(email, "Email сервис", "отправка уведомлений")
Rel(libAcc, email, "")

@enduml