@startuml Диаграмма активности
|Читатель|
start
:Авторизуется;
:Ищет книгу;

if(Книга в наличии) then(да)
    :Броирует книгу;
    :Идет в библиотеку;

    |Библиотекарь|
    :Идентифицирует читателя;

    if (Личность читателя не подтверждена?) then (нет)
        if (Подтвредить?) then (нет)
            end
        else (да)
            :Личность читателя подтверждена;
        endif
    endif

    :Выдает забронированную книгу;

    |Читатель|
    :Пользуется книгой;
    :Идет в библиотеку;

    |Библиотекарь|
    :Идентифицирует читателя;
    :Принимает книгу обратно;

    if(Возврат просрочен?) then (да)
    |Система|
    :Выписывает штраф;
    |Библиотекарь|
    :Печатает квитанцию на оплату штрафа;
    |Читатель|
    :Оплачивает штраф и
    приносит квитанцию об оплате;
    |Библиотекарь|
    :Регистрирует оплату штрафа;
    stop
    else (нет)
        stop
    endif

else (нет)
    |Читатель|
    end
endif

@enduml