@startuml
  top to bottom direction
  hide empty description
  skinparam nodesep 65
  [*] --> Pending : Начало без бронирования
  [*] --> Reservation  : \n\nНачало через бронирование
  Reservation --> Pending : Началось время бронирования
  Reservation --> Canceled : Отмена бронирования
  Canceled --> [*]
  Pending --> Invalid : Ошибка при проверке\nвозможности парковки
  Pending --> Payment : Пройдены проверки\nна возможность начала парковки
  Payment --> Invalid : Истекло время на оплату
  Payment --> Active : Совершена успешная оплата
  Active --> Completed : Истекло время парковки
  Payment --> Canceled : Ручная отмена оплаты
  Active --> Canceled : Ручная отмена парковки
  Invalid --> [*]
  Completed --> [*]
@enduml
